services:

  frontend:
    image: nginx:stable-bookworm
    container_name: nginx
    restart: always
    ports:
      - '80'
      - '443:443'
    volumes:
      - ./frontend/volume:/app
    networks:
      - transcendance
    depends_on:
      - vault
    
  nginx:
    image: nginx:stable-bookworm
    container_name: nginx
    restart: always
    ports:
      - '80'
      - '443:443'
    volumes:
      - ./frontend/volume:/app
    networks:
      - transcendance
    depends_on:
      - vault

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: always
    ports:
      - '8080'
    networks:
      - matcha
    depends_on: 
      - vault

  postgres_data:
    image : postgres:12-bookworm
    container_name: postgres
    restart: always
    ports:
      - '5432'
    env_file:
      - .env
    networks:
      - matcha

volumes:
  postgres_data:
      name : postgres_data
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '../postgres_data/'

networks:
  matcha:
    driver: bridge