services:

  frontend-nginx:
    build: frontend/.
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/volume:/var/www
    networks:
      - matcha

networks:
  matcha:
    driver: bridge
