services:

  frontend-nginx:
    build: frontend/.
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/website-react:/var/www
    networks:
      - matcha

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: always
    ports:
      - '8080'
    networks:
      - matcha
    depends_on: 
      - vault

  postgres_data:
    image : postgres:12-bookworm
    container_name: postgres
    restart: always
    ports:
      - '5432'
    env_file:
      - .env
    networks:
      - matcha

volumes:
  postgres_data:
      name : postgres_data
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '../postgres_data/'


networks:
  matcha:
    driver: bridge
