services:

  frontend:
    build: frontend/.
    container_name: frontend
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - matcha

  backend:
    build: backend/.
    container_name: backend
    restart: always
    volumes:
      - ./backend/backend-express:/app
    networks:
      - matcha
    env_file:
      - .env
    ports:
      - "3050:5000"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - matcha

  database:
    image : postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432'
    env_file:
      - .env
    networks:
      - matcha

volumes:
  postgres_data:
      name : postgres_data
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: '../postgres_data/'


networks:
  matcha:
    driver: bridge
